#amqphub.amqp10jms.remoteUrl=amqps://ex-aao-external-0-svc-rte-test.apps-crc.testing:443?transport.trustStoreLocation=/home/gferreir/Projects/Clientes/Brasilprev/implementations/amq-certs/client.ts&transport.trustStorePassword=changeit&transport.verifyHost=false
amqphub.amqp10jms.remoteUrl=amqp://ex-aao-hdls-svc.test.svc.cluster.local:61616
amqphub.amqp10jms.username=
amqphub.amqp10jms.password=
amqphub.default.queue=testQueue